[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.28"
via-ir = true
optimizer = true
optimizer_runs = 200
gas_reports = ["GoldToken", "Lotterie", "TokenBridge"]
no_match_coverage = "script/*"
ffi = true
ast = true
build_info = true
extra_output = ["storageLayout"]

[rpc_endpoints]
ethereumSepolia = "${ETHEREUM_SEPOLIA_RPC_URL}"
optimismGoerli = "${OPTIMISM_GOERLI_RPC_URL}"
avalancheFuji = "${AVALANCHE_FUJI_RPC_URL}"
arbitrumSepolia = "${ARBITRUM_SEPOLIA_RPC_URL}"
polygonMumbai = "${POLYGON_MUMBAI_RPC_URL}"
bnbChainTestnet = "${BNB_CHAIN_TESTNET_RPC_URL}"
baseSepolia = "${BASE_SEPOLIA_RPC_URL}"
metisSepolia = "${METIS_SEPOLIA_RPC_URL}"
zksyncSepolia = "${ZKSYNC_SEPOLIA_RPC_URL}"
scrollSepolia = "${SCROLL_SEPOLIA_RPC_URL}"
zircuitSepolia = "${ZIRCUIT_SEPOLIA_RPC_URL}"
xlayerSepolia = "${XLAYER_SEPOLIA_RPC_URL}"
polygonZkevmSepolia = "${POLYGON_ZKEVM_SEPOLIA_RPC_URL}"
polkadotAstarShibuya = "${POLKADOT_ASTAR_SHIBUYA_RPC_URL}"
mantleSepolia = "${MANTLE_SEPOLIA_RPC_URL}"
soneiumMinatoSepolia = "${SONEIUM_MINATO_SEPOLIA_RPC_URL}"
bsquaredTestnet = "${BSQUARED_TESTNET_RPC_URL}"
bobSepolia = "${BOB_SEPOLIA_RPC_URL}"
worldchainSepolia = "${WORLDCHAIN_SEPOLIA_RPC_URL}"
shibariumTestnet = "${SHIBARIUM_TESTNET_RPC_URL}"
bitlayerTestnet= "${BITLAYER_TESTNET_RPC_URL}"
fantomSonicTestnet = "${FANTOM_SONIC_TESTNET_RPC_URL}"
cornTestnet = "${CORN_TESTNET_RPC_URL}"
hashkeySepolia = "${HASHKEY_SEPOLIA_RPC_URL}"
inkSepolia = "${INK_SEPOLIA_RPC_URL}"
